version: "3"

services:

  persona_creation:
    build:
      context: services/personas/creation
    ports:
      - "8080:8080"
    volumes:
      - chromadb-data:/var/lib/chromadb
    networks:
      - backend
    depends_on:
      - chroma_db

  persona-conversation:
    build:
      context: services/personas/conversation
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - chroma_db

  persona-persistence:
    build:
      context: services/personas/persistence
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      - chroma_db

  #mysql:
  #  image: mysql:latest
  #  container_name: local-mysql
  #  ports:
  #    - "3306:3306"
  #  environment:
  #   MYSQL_ROOT_PASSWORD: password123
  #   MYSQL_DATABASE: microdata
  #  volumes:
  #    - mysql-data:/var/lib/mysql
  #  networks:
  #    - backend

  chroma_db:
    image: chroma:latest
    container_name: local-chromadb
    build:
      context: services/db
    ports:
      - "8083:8083"
    volumes:
      - chromadb-data:/var/lib/chromadb
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
    driver: local

  chromadb-data:
    driver: local
