version: "3"

services:

  persona-creation:
    build:
      context: services/personas/creation
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mysql

  persona-conversation:
    build:
      context: services/personas/conversation
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - mysql

  persona-persistence:
    build:
      context: services/personas/persistence
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: local-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: microdata
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  chromadb:
    image: chroma:latest
    container_name: local-chromadb
    build:
      context: services/db
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
    driver: local
